### ISSUE TITLE
[Crash]: Server Startup Crash on Fabric 1.20.1

### ISSUE THREAD

**Issue by Knito58** [MattiDragon/AdvancedNetworking#24]
### Description of the issue

The crash only happens on my Fabric server on startup when Advanced Networking is installed. Removing the mod fixes the problem.

```
[08:19:10] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: CLIENT
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc-1.20.1-loader-0.16.7-launcher-1.0.1.jar:1.0.1]
Caused by: java.lang.NoSuchFieldError: CLIENT
	at io.github.mattidragon.nodeflow.graph.context.ContextType.<clinit>(ContextType.java:41) ~[nodeflow-0.2.2+mc.1.20.1-98ebe2379b27f61.jar:?]
	at io.github.mattidragon.advancednetworking.AdvancedNetworking.<clinit>(AdvancedNetworking.java:34) ~[advanced-networking-2.0.3+mc.1.20.1.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.7.jar:?]
	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:73) ~[supermartijn642corelib-1.1.17a-fabric-mc1.20.1.jar:?]
	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:75) ~[supermartijn642corelib-1.1.17a-fabric-mc1.20.1.jar:?]
	at net.minecraft.server.Main.handler$dho000$supermartijn642corelib$beforeInit(Main.java:2526) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	... 4 more

```
https://pastebin.com/CbccQnsf

### Reproduction steps

Copy mod file in server's mod folder and restart.

### Mod version

2.0.3 mc 1.20.1

### Operating System

Windows 11 Pro

### Minecraft version

1.20.1

### Other mods

Extended Drawers

### Server

Happens

### Client

Doesn't happen

### Logs

https://pastebin.com/CbccQnsf

### Crash Report

https://pastebin.com/CbccQnsf

**Comment by MattiDragon** [comment]
The 1.20.1 version is no longer receiving updates. You can work around this issue by installing the latest version of nodeflow.

It can only be found in github releases for 1.20.1.

**Comment by Knito58** [comment]
I do not find nodeflow as a separated jar. Can you guide me through the process of getting nodeflow?
As I understood I would pop this one into the mods folder of the server.

**Comment by MattiDragon** [comment]
You can download the jar from here: https://github.com/MattiDragon/nodeflow/releases/tag/v0.2.3-mc.1.20
